/** @format */

import Head from "next/head";

import UiUxResources from "@/components/layouts/UiUxResources";
import ContentHeader from "@/components/uiuxresourses/InnerPage/ContentHeader";
import Resources from "@/components/uiuxresourses/InnerPage/Resources";

import UiUxResourcesServices from "@/services/uiUxResources.services";

const Slug = ({ data }) => {
  return (
    <>
      <Head>
        <title>{`${data?.Category?.name} - ${data?.name}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UiUxResources >
        {data && (
          <>
            <ContentHeader
              categoryName={data?.Category?.name}
              subCategoryName={data?.name}
              subCategoryDescription={data?.description}
            />
            
            <Resources innerPages={data?.InnerPage || []} />
          </>
        )}
      </UiUxResources>
    </>
  );
};

export async function getServerSideProps(ctx) {
  try {
    const { slug } = ctx.params;
    const subCategoryReq = await UiUxResourcesServices.getSubCategoryByName(
      slug
    );
    const [{ data }] = await Promise.all([subCategoryReq]);

    return {
      props: {
        data: data?.data,
      },
    };
  } catch (error) {
    console.log(error);
    return {
      props: {
        data: null,
      },
    };
  }
}

export default Slug;
